### ISSUE TITLE
Remote application protocol out of date. Update application

### ISSUE THREAD

**Issue by anthonyeden** [greyshirtguy/Pro7RemoteMiddleMan#2]
When connecting to ProPresenter 7.4.2, I get this error message:

Master Said: {"controller":0,"authenticated":0,"error":"Remote application protocol out of date. Update application","majorVersion":7,"minorVersion":4,"protocol":701,"action":"authenticate"}

This looks fairly simple to bump the version number, but I'm not setup with a .NET environment right now so I can't test. Could you build a new EXE with this updated?

**Comment by greyshirtguy** [comment]
whoops - I forgot about this! I'll fix it
Ps - I have added same functionality in latest Companion module if you prefer....

**Comment by anthonyeden** [comment]
@greyshirtguy Cool, thanks.
That's interesting. I didn't know it was in the Companion module. The advantage of this one I guess is it's just a single EXE to run on one of my Pro7 machines :)

**Comment by greyshirtguy** [comment]
Fixed in [Release 1.0.0.1](https://github.com/greyshirtguy/Pro7RemoteMiddleMan/releases/tag/1.0.0.1)

**Comment by anthonyeden** [comment]
You beaut! This works a charm! I'll give it a go tomorrow morning.
