### ISSUE TITLE
Slave does not respond to requests.

### ISSUE THREAD

**Issue by planegeek63** [greyshirtguy/Pro7RemoteMiddleMan#3]
App verifies connection between master and slave. Slide changes on the master side are detected, and the software claims to send the signal to the slave. Slave does not respond to triggers by the software/network.

I cannot get the slave machine to update or change slides.

**Comment by greyshirtguy** [comment]
Hello,
I just tested and it worked fine for me (using Pro7 on Windows as the leader and PRo7 on Mac as follower).
The code is pretty simple and there aren't really any config options to set wrong and make it not work... - it should just work.

Some things to check:
Review your debug log....
You want to see a:
`Forwarding commmand to follower: {"action" :"presentationTriggerIndex"...........`
being sent to the follower for each slide you click...
and then the follower responding with:
`Follower presententationSlideIndex: `

The number (slide index should match)


![image](https://user-images.githubusercontent.com/1886513/126719127-6d9f3142-e63d-4e50-bb13-bcc97f97785d.png)


If you are seeing the messages being forwarded "Forwarding commmand" but no response, then you want to check the setup of  your follower..... are your playlists *exactly* the same -  it's all done by numbers (not names) - so the number of playlist folders, playlists and presentations in those playlist has to match exactly

**Comment by planegeek63** [comment]
I had used the non-viable product .exe you created, and yes, our Playlists
are exact replicas on both machines. It just appears one is not actually
performing the changes but the .exe says it is receiving.

**Comment by planegeek63** [comment]
![image](https://user-images.githubusercontent.com/87823521/126826714-b8d0ab27-7f0a-4128-9f0c-ed0e25bf074e.png)

**Comment by planegeek63** [comment]
I'll note, I had a family member who is familiar with C# look at the program, and he verifies that the 2 computers are connected via WebSocket, but the actual command is not being sent to the slave machine. 

This is the current setup:

iMac Pro7 running main show > Windows Machine running middleman > different iMac Pro7 running livestream.

**Comment by greyshirtguy** [comment]
Oh dear - I am so sorry that I was on the wrong planet!!!
I thought I was answering an issue for a _different product!!!_ (I have updated Companion module to provide the same function as this app )

Now... back to _your issue_ !
Let me check the app on my setup and see if something has changed in later versions of Pro7

**Comment by greyshirtguy** [comment]
I just tested using Pro7 on different compupter as slave...and it worked for me now...
Can you copy and paste the full log to share it here?

Click anywhere in the text log... press CTRL-A to select all and then copy that (CTRL-C)...

![image](https://user-images.githubusercontent.com/1886513/126852184-7d3b390c-2f77-4acf-9fa4-5d3d311bc751.png)

**Comment by greyshirtguy** [comment]
I've got a feeling this will be difficult to solve without me seeing the issue live....(since it works fine for me here - so I have no issue to look at for myself)

If you want, I am happy to setup a voice-call & remote desktop session to chat and while we look at the problem together live.
My timezone is Sydney, Australia (yep, I am in lockdown)......We would have to find a timeslot that works for us both (I am happy to do late evenings).

Side note: I'm also tempted to say "use the ProPresenter module in the Companion software instead" cause it does the same thing and so, so much more....and I am much more actively working on that. (Note: I don't think using differnt software for master-slave it would solve _this problem_ you are having though - as I suspect it's outside the sofware, so swapping software would probably  not elimate it)

**Comment by planegeek63** [comment]
I'm located in the GMT - 4 timezone, Eastern Standard Time in New York. I would be happy to try and pick a time for both of us, or even switching to the companion module, but I am not entirely computer literate when it comes to running uncompiled software like that. We just upgraded to Pro7 from Pro6, and we are trying to mimic the setup we had with that software (we are trying to use this setup for a church environment)

**Comment by greyshirtguy** [comment]
Here are some time slots that work for me.

![image](https://user-images.githubusercontent.com/1886513/126853693-acf4644a-a3a2-4419-b12e-7ab56bcfaeb3.png)

We could chat using an app on Mobile (FB messanger, Google Voice, Skype etc - let me know what suits you)...
And share desktop via Google Chrome Remote Desktop. (Assuming your Computers have chrome installed).
(Will likey want to look at the Windows desktop running this app and the slave Mac)

in meantime, can you share screenshots fully expanded playlists from both macs? (and that log text from the app?)

**Comment by planegeek63** [comment]
Will do, I will send that over when I get into the building tomorrow. I
likely won't be around until late next week, but I'll try to give you as
much info as possible.

**Comment by greyshirtguy** [comment]
Late next week suits me even better ! if you have time to chat & share desktop - we can solve this!

**Comment by planegeek63** [comment]
Hi, I'm around in about an hour if that works for you, let me know!

**Comment by greyshirtguy** [comment]
Still around?
https://meet.google.com/cjg-sihb-wov

**Comment by greyshirtguy** [comment]
Closing this issue (as we discovered there was a slight mismatch in playlist/folder indexing)
