### ISSUE TITLE
Pro7.7 clears video between slides

### ISSUE THREAD

**Issue by ChristopherKossatz** [greyshirtguy/Pro7RemoteMiddleMan#6]
With the new ProPresenter 7.7 Update with custom cleargroups, it seems like Pro7 sends a "clearVideo" command between changing slides. This command is not triggered manual nor triggered from the action palett or similar. It seems like ProPresenter added this command to the default slide changing procedure. This makes for some very laggy transitions on the slave side, as the slide is first cleared and then the new one is triggered. In some rare occasions the slide will first be changed and then cleared, which clears the whole screen and its black. This seems to be a sync issue with commands that are closely timed.

ProPresenter 7.7:
```
Master Said: {"action":"clearText"}
Master Said: {"action":"clearVideo"}
Telling Slave: {"action":"clearVideo"}
Master Said: {"slideIndex":2,"presentationPath":"1:2","action":"presentationTriggerIndex"}
Telling Slave: {"action":"presentationTriggerIndex","slideIndex":"2","presentationPath":"1:2"}
```

Propresenter 7.6.1 doesn't send the "clearVideo" between Slides:
```
Master Said: {"action":"clearText"}
Master Said: {"slideIndex":2,"presentationPath":"1:2","action":"presentationTriggerIndex"}
Telling Slave: {"action":"presentationTriggerIndex","slideIndex":"2","presentationPath":"1:2"}
```

Is there a way to filter the "clearVideo"?

**Comment by greyshirtguy** [comment]
I am assuming you are running the Pro7 "Leader" on Windows? (I only see those etxtra clear msgs comming from Pro7 on Windows).

Also, I only see them when the media is set to **foreground** (theyare not sent if the media is set as **background**)

As I think about it - it _kinda_ makes sense to clear the video whenever a foreground video is (re)triggered.
Can you confirm if your media is foreground/background?
Are you able to set to background? or do you have  use-case where you *want* it as foreground and not the send a clear?

**Comment by ChristopherKossatz** [comment]
Yes the Master is Windows running on Windows, Slave is running on Mac. When i reported this all media was put to foreground. 
I switched the "Media Action Behavior" to background, but this makes it worse. The transition is more laggy than before. 

```
Master Said: {"action":"clearVideo"}
Telling Slave: {"action":"clearVideo"}
Master Said: {"action":"clearText"}
Telling Slave: {"action":"clearText"}
Master Said: {"slideIndex":2,"presentationPath":"1:3","action":"presentationTriggerIndex"}
Telling Slave: {"action":"presentationTriggerIndex","slideIndex":"2","presentationPath":"1:3"}
Slave Said: {"action":"clearText"}
Slave Said: {"action":"clearText"}
Slave Said: {"action":"clearText"}
Slave Said: {"action":"clearText"}
Slave Said: {"presentationDestination":0,"action":"presentationTriggerIndex","presentationPath":"1:3","slideIndex":2}
```
(I didn't trigger the ClearText on the Slave side. It just went off automatically after the transition.. )

I also tried the "Convert Media Action to Slide Element" option, and it didn't send the "clearVideo" in this case. Unfortunately this doesn't work for my use-case as i am outputting the Media and Slide Layers to different Outputs (for Stream and In-house service)

**Comment by greyshirtguy** [comment]
Eeek. I can’t get my copy of Pro7.7 on windows to send those same messages once the media is set to background. 

I’m about to get some sleep too. 

Happy to look into this and get to the bottom of it!

when you can, can you share:

exact version of Pro7 master. 
Screenshot (video) of you clicking slides in master
Details of the document cues in master (maybe even a copy?)

I’m trying to get enough info to replicate issue at my end tomorrow.

**Comment by ChristopherKossatz** [comment]
Propresenter 7.7. (Build 117899279) Same Version and Build on both machines.
https://we.tl/t-0Z0PBnFNT2 (different Pictures that were used in the clips)

https://youtu.be/q6ADSwSVqe0 With Slides in Foreground Mode
https://youtu.be/gPcq95GaNsk With Slides in Background Mode

**Comment by greyshirtguy** [comment]
phew, I can replicate - please bear with me, we'll hopefully get this sorted soon!

**Comment by greyshirtguy** [comment]
[Pro7RemoteMiddleMan.zip](https://github.com/greyshirtguy/Pro7RemoteMiddleMan/files/7409615/Pro7RemoteMiddleMan.zip)
Here is an updated version that *tries* to workaround the issue - as best I could think of for now...

Can you try this version and report back?  If it works okay for you, I'll update repository code and add a new release.

The new logic is to WAIT a short time before passing any clear (text or video) message to slave and to cancel sending that clear message IF it sees that a slide is quickly triggered soon after the clear message (during the short wait time).

Default wait time is 300msec (for now, it's configurable by manually adding some XML to a setting file)

This way, when you click a slide and it causes some clear(Text/Video) messages to be sent just before the slide trigger message, the act of waiting will (hopefully) notice the triggered slide and not forward the clear messages to slave.

If you click a clear (text/video) button without quickly following it with a triggered slide, then the master will send the clear message to the slave (after waiting 300msec)

**Comment by ChristopherKossatz** [comment]
Hey, sorry for the delayed response. I updated to the new version and it worked very well! All transitions are smooth and the message filtering works really well! I couldn't find were to configure the wait time.

Thanks for your quick response and solution!
